name: Build and run npm test 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t hurtigcodes/docker-react-gh-gcp -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true hurtigcodes/docker-react-gh-gcp npm test