name: Deploy to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t hurtigcodes/docker-react-gh-gcp -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true hurtigcodes/docker-react-gh-gcp npm test

      - run: docker build -t hurtigcodes/multi-client ./client
      - run: docker build -t hurtigcodes/multi-nginx ./nginx
      - run: docker build -t hurtigcodes/multi-server ./server
      - run: docker build -t hurtigcodes/multi-worker ./worker

      - run: docker push hurtigcodes/multi-client
      - run: docker push hurtigcodes/multi-nginx
      - run: docker push hurtigcodes/multi-server
      - run: docker push hurtigcodes/multi-worker
